---
- hosts: cluster_nodes
  become: true
  become_method: sudo
  tasks:
    - name: Initiate Node restarts
      reboot:
        reboot_timeout: 3600
      
    - name: Waiting for the machine(s) to come back
      local_action: 
        module: wait_for 
          host={{ ansible_host }} 
          state=started
          port=22
          delay=60
      become: false

    - name: Verify node uptime
      shell: "uptime"
      async: 60
      poll: 1
      register: uptime

    - debug: var=uptime.stdout_lines
