---
- hosts: cluster_nodes
  become: true
  become_method: sudo
  tasks:
    - name: Initiate Node restarts
      reboot:
        reboot_timeout: 3600

    - name: Waiting for Nodes to reconnect
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 300

    - name: Verify node uptime
      shell: "uptime"
      register: uptime

    - debug: var=uptime.stdout_lines
