---
- hosts: cluster_nodes
  become: true
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Initiate node restarts
      reboot:
        reboot_timeout: 3600

    - name: Waiting for nodes to reconnect
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 300

    - name: Verify node uptime
      shell: "uptime"
      register: Uptime

    - debug: var=Uptime.stdout_lines
