---
- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Set timezone to Pacific
      shell: timedatectl set-timezone America/Los_Angeles

    - name: Verify current date
      shell: printf $(date +'%m/%d/%Y @ %I:%M %p\n')
      register: date

    - name: Verify current time
      shell: echo $(date  +"%r")
      register: time

    - debug:
        msg:
        - "Date: {{ date.stdout }}"
        - "Time: {{ time.stdout }}"