---
- hosts: all
  become: true
  become_method: sudo
  gather_facts: yes
  tasks:
  - name: Checking for updates
    apt: update_cache=yes

  - name: Upgrading system apps
    apt: upgrade=dist
    
  - name: Check if reboot is required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  # ref http://stackoverflow.com/a/35169496
  - name: Notify of pending reboot
    pause:
      prompt: "Press ENTER to reboot {{ item }} now, or Ctrl+C to abort."
    when: "'reboot_required_file' in hostvars[item] and hostvars[item]['reboot_required_file'].stat.exists"
    with_items: "{{ play_hosts }}"
  
  # ref https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
  - name: Rebooting machine
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
    when: reboot_required_file.stat.exists
  
  - name: Waiting for the machine to come back
    local_action: wait_for host={{ ansible_host }} state=started port=22 delay=30
    become: no
    when: reboot_required_file.stat.exists

  - name: Verify node uptime
    shell: "uptime"
    register: uptime

  - debug: var=uptime.stdout_lines
