---
- hosts: k3s_cluster
  become: true
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Ensure the Raspberry Pi temperature script is installed
      ansible.builtin.import_tasks: tasks/ensure-pi-temps.yaml
  tasks:
    - name: Getting Pi cluster temperatures
      ansible.builtin.command: /usr/local/bin/pi-temps.sh
      register: output
    - ansible.builtin.debug:
        var: output.stdout_lines
