---
- hosts: testers
  become: yes
  tasks:
  - name: Checking for updates
    apt: update_cache=yes

  - name: Upgrading system apps
    apt: upgrade=dist

  - name: Install Packages
    apt:
      pkg:
        - apt-transport-https
        - python3-pip

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker module for Python
    pip:
      name: docker

  - name: Setup Rancher docker image
    docker_container:
      name: rancher
      image: rancher/rancher
      restart_policy: always
      state: started
      exposed_ports:
        - '80'
        - '443'
      ports:
        - '80:80'
        - '443:443'