---
- name: Install and run Rancher
  hosts: "{{ target_hosts | default('managed_hosts') }}"
  become: true
  gather_facts: false
  pre_tasks:
    - name: Ensure Docker is installed and ready
      ansible.builtin.import_tasks: tasks/ensure-docker.yaml
  tasks:
    - name: Run the Rancher container
      community.docker.docker_container:
        name: rancher
        image: rancher/rancher
        restart_policy: always
        state: started
        exposed_ports:
          - '80'
          - '443'
        ports:
          - '80:80'
          - '443:443'
