---
- name: Reboot selected hosts
  hosts: "{{ target_hosts | default('k3s_workers') }}"
  become: true
  gather_facts: false
  tasks:
    - name: Reboot hosts and wait for them to return
      ansible.builtin.reboot:
        reboot_timeout: 3600

    - name: Verify node uptime
      ansible.builtin.command: uptime
      changed_when: false
      register: uptime

    - name: Display node uptime
      ansible.builtin.debug:
        var: uptime.stdout_lines
